service: laravel

provider:
  name: aws
  #  vpc:
  #    securityGroupIds:
  #      - sg-0ddd2f27eec1e3126
  #    subnetIds:
  #      - subnet-037dcb355ceb7a124
  #      - subnet-066e124b81eaeb6dd
  #      - subnet-051b0ebebce823bff
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  region: ap-southeast-1
  httpApi:
    cors: true
  # Environment variables
  environment:
    APP_ENV: ${sls:stage}
    APP_NAME: ${env:APP_NAME}
    APP_KEY: ${env:APP_KEY}
    APP_DEBUG: true
    APP_URL: ${env:APP_URL}
    LOG_CHANNEL: stack
    LOG_DEPRECATIONS_CHANNEL: null
    LOG_LEVEL: debug
    DB_CONNECTION: ${env:DB_CONNECTION}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    FILESYSTEM_DISK: local
    QUEUE_CONNECTION: sync
    SESSION_DRIVER: file
    SESSION_LIFETIME: 120
    MEMCACHED_HOST: ${env:MEMCACHED_HOST}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    REDIS_PORT: ${env:REDIS_PORT}
    MAIL_MAILER: ${env:MAIL_MAILER}
    MAIL_HOST: ${env:MAIL_HOST}
    MAIL_PORT: ${env:MAIL_PORT}
    MAIL_USERNAME: ${env:MAIL_USERNAME}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    MAIL_ENCRYPTION: null
    MAIL_FROM_ADDRESS: ${env:MAIL_FROM_ADDRESS}
    MAIL_FROM_NAME: ${env:APP_NAME}
    AWS_USE_PATH_STYLE_ENDPOINT: false
    PUSHER_APP_ID:
    PUSHER_APP_KEY:
    PUSHER_APP_SECRET:
    PUSHER_HOST:
    PUSHER_PORT: 443
    PUSHER_SCHEME: https
    PUSHER_APP_CLUSTER: mt1
    VITE_APP_NAME: ${env:APP_NAME}
    STRIPE_KEY: ${env:STRIPE_KEY}
    STRIPE_SECRET: ${env:STRIPE_SECRET}
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}

package:
  # Files and directories to exclude from deployment
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'

functions:

  # This function runs the Laravel website/API
  web:
    handler: public/index.php
    runtime: php-82-fpm
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    events:
      - httpApi:
          path: "*"
          method: "*"

  # This function lets us run artisan commands in Lambda
  artisan:
    handler: artisan
    runtime: php-82-console
    timeout: 720 # in seconds
    # Uncomment to also run the scheduler every minute
    #events:
    #    - schedule:
    #          rate: rate(1 minute)
    #          input: '"schedule:run"'

plugins:
  - ./vendor/bref/bref
  - serverless-lift

constructs:
  website:
    type: server-side-website
    domain: ${env:APP_DOMAIN}
    certificate: arn:aws:acm:us-east-1:092355519212:certificate/1e692055-cf44-4ad4-81bf-bc5480a2a331
    assets:
      '/build/*': public/build/
      'favicon.ico': public/favicon.ico
      'robots.txt': public/robots.txt
    forwardedHeaders:
      - Accept
      - Accept-Language
      - Content-Type
      - Origin
      - Referer
      - User-Agent
      - X-Forwarded-Host
      - X-Requested-With
      # Laravel Framework Headers
      - X-Xsrf-Token
      - X-Csrf-Token
      - X-Inertia
      - X-Inertia-Version
      # add here any file or directory that needs to be served from S3
